#!/usr/bin/env bash
# AXTESYS: regenerate the Homebrew UI cask on release.
#
# GoReleaser auto-pushes the CLI *formula* (netbird.rb) to the tap, but not the
# UI *cask*. axtesys ships upstream's SIGNED macOS UI because we don't
# sign macOS apps, so the cask must point at the matching upstream signed release
# — this script renders Casks/netbird-ui.rb for the upstream version behind our
# -axt tag and pushes it to the tap. Skips gracefully if upstream published no
# signed UI for that version (so it never fails the release).
#
# Env: GITHUB_REF_NAME (the tag, e.g. v0.73.2-axt), HOMEBREW_TAP_GITHUB_TOKEN.
set -euo pipefail

TAG="${GITHUB_REF_NAME:?GITHUB_REF_NAME not set}"
UPSTREAM_VER="${TAG#v}"; UPSTREAM_VER="${UPSTREAM_VER%%-*}"   # v0.73.2-axt -> 0.73.2
BASE="https://github.com/netbirdio/netbird/releases/download/v${UPSTREAM_VER}"
TAP_REPO="axtesys/netbird-homebrew-tap"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Fetch upstream's signed UI zips to hash them (their sha256 isn't in upstream's
# checksums file — signing happens post-build). Missing => skip, don't fail.
for arch in amd64 arm64; do
  if ! curl -fsSL -o "${tmp}/${arch}.zip" \
        "${BASE}/netbird-ui_${UPSTREAM_VER}_darwin_${arch}_signed.zip"; then
    echo "::warning::no upstream signed UI for ${UPSTREAM_VER} (${arch}); skipping cask update"
    exit 0
  fi
done
SHA_AMD64="$(sha256sum "${tmp}/amd64.zip" | cut -d' ' -f1)"
SHA_ARM64="$(sha256sum "${tmp}/arm64.zip" | cut -d' ' -f1)"

git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/${TAP_REPO}.git" \
  "${tmp}/tap"

# The url lines use the cask's own #{version} interpolation, so only the version
# and the two checksums vary per release.
cat > "${tmp}/tap/Casks/netbird-ui.rb" <<EOF
# Netbird's UI Client Cask Formula
# AXTESYS: auto-generated by release_files/update-ui-cask.sh — points at the
# upstream SIGNED macOS UI matching our -axt release. Do not edit by
# hand; changes are overwritten on the next release.
cask "netbird-ui" do
  version "${UPSTREAM_VER}"

  if Hardware::CPU.intel?
      url "https://github.com/netbirdio/netbird/releases/download/v#{version}/netbird-ui_#{version}_darwin_amd64_signed.zip"
      sha256 "${SHA_AMD64}"
      app "netbird_ui_darwin", target: "Netbird UI.app"
  else
      url "https://github.com/netbirdio/netbird/releases/download/v#{version}/netbird-ui_#{version}_darwin_arm64_signed.zip"
      sha256 "${SHA_ARM64}"
      app "netbird_ui_darwin", target: "Netbird UI.app"
  end

  depends_on formula: "netbird"

  postflight do
    set_permissions "/Applications/Netbird UI.app/installer.sh", '0755'
    set_permissions "/Applications/Netbird UI.app/uninstaller.sh", '0755'
  end

  postflight do
    system_command "#{appdir}/Netbird UI.app/installer.sh",
                   args: ["#{version}"],
                   sudo: true
  end

  uninstall_preflight do
    system_command "#{appdir}/Netbird UI.app/uninstaller.sh",
                   sudo: false
  end

  name "Netbird UI"
  desc "Netbird UI Client"
  homepage "https://www.netbird.io/"
end
EOF

cd "${tmp}/tap"
if git diff --quiet -- Casks/netbird-ui.rb; then
  echo "netbird-ui cask already at ${UPSTREAM_VER}; nothing to push"
  exit 0
fi
git config user.name  "Netbird"
git config user.email "dev@netbird.io"
git add Casks/netbird-ui.rb
git commit -m "Bump netbird-ui cask to ${UPSTREAM_VER} (upstream signed UI)"
git push origin HEAD:main
echo "pushed netbird-ui cask ${UPSTREAM_VER} to ${TAP_REPO}"
